server {
    listen 80;

    # 轉發到前台 Vue
    location / {
        proxy_pass http://website-frontend:80;
    }

    # 轉發到後台 Vue (假設後台路徑是 /admin)
    location /admin {
        proxy_pass http://admin-frontend:80;
    }

    # 轉發到 API (可依需求區分 website-api 或 admin-api)
    location /api/v1 {
        proxy_pass http://website-backend:8000;
    }
}